### ISSUE TITLE
Mise à jour RGPD du site Archifiltre

### ISSUE THREAD

**Issue by OMoukoko** [SocialGouv/archifiltre-site#137]
Hello l'équipe,

Nous avons parcouru le site Archifiltre pour nous assurer de la mise en conformité à instant T.
Vous serait-il possible de :
- installer les mentions légales au format qui convient, qui est dans le nextcloud de la Fabrique ; 
- installer la politique de confidentialité, qui n'est pas sur le site.

Vous trouverez les deux documents à installer dans le dossier "RGPD - Archifiltre" du nextcloud de la Fabrique.

Très cordialement,

Osiris Moukoko Priso.

**Comment by Alezco** [comment]
@OMoukoko La PR #153 corrige ces problèmes : 
- La page "Mentions légales" contient désormais les mentions légales mise à jour et la nouvelle politique de confidentialité
- Le bandeau de cookies a été retiré (vu avec @ThomasMenant) car aucune donnée personnelle n'est remontée

**Comment by OMoukoko** [comment]
Bonjour @Alezco 

* Pour le bandeau, oui parfait ;
* Pour les mentions légales et la politique de confidentialité, je ne vois aucun changement :

<img width="1433" alt="Capture d’écran 2021-03-05 à 16 01 16" src="https://user-images.githubusercontent.com/79263610/110133575-bf3a4700-7dcc-11eb-827d-648ee2429747.png">
<img width="1435" alt="Capture d’écran 2021-03-05 à 16 01 27" src="https://user-images.githubusercontent.com/79263610/110133583-c06b7400-7dcc-11eb-9156-dcb8c1b4efb7.png">

De même la politique de confidentialité ne figure pas sur la page que j'affiche.

Très cordialement,

Osiris Moukoko Priso

**Comment by Alezco** [comment]
Oui, la fonctionnalité n'a pas encore été validée et envoyée en production, mais ça ne saurait tarder !

**Comment by Alezco** [comment]
Bonjour @OMoukoko ! La mise à jour est en ligne et disponible ici : https://archifiltre.fabrique.social.gouv.fr/mentions-legales/

**Comment by OMoukoko** [comment]
Salut @Alezco ,

Petite incompréhension, il faut faire deux pages distinctes, une relative à la politique de confidentialité et une relative aux mentions légales.
Ainsi sur la page "mentions légales", il ne devrait y avoir que les mentions légales et sur la page "politique de confidentialité", il faudrait y déplacer la politique de confidentialité.

Très cordialement,

Osiris Moukoko Priso

**Comment by Alezco** [comment]
Je corrige ça et je reviens vers toi quand la mise à jour sera en ligne

**Comment by Alezco** [comment]
Bonjour, la mise à jour est en ligne :
- https://archifiltre.fabrique.social.gouv.fr/mentions-legales
- https://archifiltre.fabrique.social.gouv.fr/politique-de-confidentialite

**Comment by OMoukoko** [comment]
Salut,Ok, parfait
